var chips=JSON.parse(`{"chips":[
{
"name":"atmega8",
"signature":"01e907",
"flash_size":"",
"eeprom_size":"",
"pagesize_flash":"",
"pagesize_eeprom":"",
"wordsize_flash":"",
"wordsize_eeprom":"",
"twd_fuse":"",
"twd_flash":"",
"twd_eeprom":"",
"twd_erase":""
},
{
"name":"atmega88",
"signature":"01e907",
"flash_size":"",
"eeprom_size":"",
"pagesize_flash":"",
"pagesize_eeprom":"",
"wordsize_flash":"",
"wordsize_eeprom":"",
"twd_fuse":"",
"twd_flash":"",
"twd_eeprom":"",
"twd_erase":""
}
]}`);