var chips=JSON.parse(`{"chips":[
{
"name":"atmega8",
"signature":"1e9307",
"flash_size":4096,
"eeprom_size":512,
"pagesize_flash":32,
"pagesize_eeprom":4,
"wordsize_flash":2,
"wordsize_eeprom":1,
"twd_fuse":4.5,
"twd_flash":4.5,
"twd_eeprom":9,
"twd_erase":9,
"fuse":2
},
{
"name":"atmega88",
"signature":"01e907",
"flash_size":"",
"eeprom_size":"",
"pagesize_flash":"",
"pagesize_eeprom":"",
"wordsize_flash":"",
"wordsize_eeprom":"",
"twd_fuse":"",
"twd_flash":"",
"twd_eeprom":"",
"twd_erase":""
}
]}`);
